### ISSUE TITLE
[pbr][wish] support adguardhome.ipset as resolver_set option

### ISSUE THREAD

**Issue by bonuzzz** [stangri/openwrt_packages#167]
Steps in adguardhome side:
1. in config file add to parameter ipset_file path to ipset file. Example: ipset_file: "/tmp/ipset"

Steps in pbr side:
1. create ipset lists (ipset create hash:ip) (/tmp/ipset)
2. create new file with ipset list. format   domain/ipset_name
Example:
```
themoviedb.org/pbr_vpn_4_dst_ip_cfg0f6ff5 
tmdb.org/pbr_vpn_4_dst_ip_cfg0f6ff5 
```
3. reload adguardhome service.   /etc/init.d/adguardhome reload or /usr/bin/AdGuardHome -s reload

I remember current agh version in openwrt doesn't support ipset file yet, but I write this manual until I remember how to do it.
Subdomains work with agh like in dnsmasq.
you will get error at adguadhome start  if you write ipset in agh ipset file, which doesn't exist in ipset list
The logic here is the same as in dnsmasq except different file format

Some attention with adguardhome: when ipset file mentioned in config doesn't exist, agh checks it at starting and if it doesn't exist or with wrong format, it will stopped with fatal error. Blank file is right there.
I see agh starts before pbr and if file placed in tmp, ipset file haven't created by that time.

**Comment by stangri** [comment]
Just linking the previous conversation for posterity: https://github.com/stangri/source.openwrt.melmac.net/issues/166

**Comment by stangri** [comment]
> Steps in pbr side:
> 
> 1. create ipset lists (ipset create hash:ip) (/tmp/ipset)
> 2. create new file with ipset list. format   domain/ipset_name
>    Example:
> 
> ```
> themoviedb.org/pbr_vpn_4_dst_ip_cfg0f6ff5 
> tmdb.org/pbr_vpn_4_dst_ip_cfg0f6ff5 
> ```

From what I gathered from AGH docs, all their config/ipset files are yaml, not plain text, so it's going to be more complicated than that and that's why I need someone with working AGH 0.107.13 and later to run some tests first.

I've already refactored a lot of `pbr` code to support resolver sets other that dnsmasq.ipset and dnsmasq.nftset, but I need an example of the working config before I can implement support for AGH.ipset.

**Comment by bonuzzz** [comment]
config file is yaml, but ipset file is plain text. I'm using this method since our last conversation. I made dirty workaround for now: replaced in init script to readonly dnsmasqFile="/var/ipset_agh" and echo "${param}/${ipset4}${ipset6:+,$ipset6}" >> "$dnsmasqFile" && ipv4_error=0 and restart adguardhome with dnsmasq

**Comment by bonuzzz** [comment]
I have where to test if needed

**Comment by stangri** [comment]
Can you post your adguardhome config file?

**Comment by bonuzzz** [comment]
[AdGuardHome.zip](https://github.com/stangri/source.openwrt.melmac.net/files/10026254/AdGuardHome.zip)


I also added generated ipset file
[ipset_agh.zip](https://github.com/stangri/source.openwrt.melmac.net/files/10026335/ipset_agh.zip)

**Comment by stangri** [comment]
Is there an `adguardhome` binary on the system? Does it report version and/or features somehow?

**Comment by stangri** [comment]
Install `pbr 0.9.9-28` and `luci-app-pbr 0.9.9-28` and clear your browser cache (otherwise it won't pick up changes in the luci app), you should be able to select AdGuardHome ipset from the resolver set options.

**Comment by bonuzzz** [comment]
Issues:
1. https://github.com/stangri/source.openwrt.melmac.net/blob/master/pbr/files/etc/init.d/pbr.init#L661
Should be: echo "${param}/${ipset4}${ipset6:+,$ipset6}" >> "$aghIpsetFile" && ipv4_error=0

2. I have service error in luci: nft 'add rule inet fw4 pbr_prerouting ip daddr @pbr_warp_4_dst_ip_cfg086ff5 goto pbr_mark_0x040000 comment "ifconfig"'

In console when I type that command:
<img width="710" alt="Screenshot 2022-11-18 at 19 13 34" src="https://user-images.githubusercontent.com/6509127/202750680-71605630-5f4d-42f1-9800-1a0e835a3aed.png">

3. Something wrong with checking the existence of adguardhome.  I cut it from init and luci.pbr to get working.

**Comment by stangri** [comment]
Fixed detection/choice to use nft and the AGH ipset file format in `pbr 0.9.9-33`.

For AGH detection, please post the output of:
```
command -v AdGuardHome
ls -la /etc/AdGuardHome.yaml
```

**Comment by bonuzzz** [comment]
<img width="653" alt="Screenshot 2022-11-18 at 20 10 20" src="https://user-images.githubusercontent.com/6509127/202762417-61d4b818-2ddc-41e9-99e0-808d3da14b61.png">
I have clean install only with adguardhome and pbr, luci-app-pbr

command -v AdGuardHome
/usr/bin/AdGuardHome/AdGuardHome

ls -la /etc/AdGuardHome.yaml
-rw-r--r--    1 root     root          4921 Nov 18 19:31 /etc/AdGuardHome.yaml

**Comment by bonuzzz** [comment]
Everything works except compatibility checking. I got Resolver set support (adguardhome.ipset) is enabled in pbr, but this resolver set is not supported on this system!

Give me some time. I will try to determine what caused it. Anyway main functionality is working

**Comment by bonuzzz** [comment]
Adguardhome doesn't allow comments in ipset file.
Example: iplocation.net/pbr_france_4_dst_ip_cfg096ff5

What about compatibility check, I thought it was version compare condition, but it have to cut all check from both files.
As I see, both init and luci files have this check. Is it possible to show in /etc/init.d/pbr status what resolver sets currently supported without using luci?

**Comment by bonuzzz** [comment]
Init script has issue only with ipset file format. I wrote about it before.
Luci (luci.pbr) script has compatibility check issue.

I reinstalled everything and tested only with pbr package without luci

**Comment by bonuzzz** [comment]
I attached my modifications. Maybe you will have any ideas what's wrong there
[pbr.zip](https://github.com/stangri/source.openwrt.melmac.net/files/10044638/pbr.zip)

**Comment by stangri** [comment]
Have you installed AGH as an OpenWrt package or manually (I strongly suspect latter)? What's the output of `AdGuardHome --version`?

**Comment by bonuzzz** [comment]
Manually. I use luci-app-adguardhome, which installs and updates bin.
AdGuard Home, version v0.107.18

upd: I've tried 0.9.9-34 version (clean install) and I see again "Please note that adguardhome.ipset is not supported on this system." in luci

If needed, I could install adguardhome ipk from master

**Comment by stangri** [comment]
What's the output in CLI?

To confirm the support for `adguardhome.ipset` option, it does the following:
```sh
readonly agh="$(command -v AdGuardHome)"
readonly aghConfigFile='/etc/AdGuardHome.yaml'

					if [ -n "$agh" ] && [ -s "$aghConfigFile" ]; then
						agh_version="$($agh --version | sed 's|AdGuard Home, version v0\.\(.*\)|\1|')"
						if is_greater_or_equal "$agh_version" '107.13'; then
							resolver_set_supported='true'
echo 'success'!
						else
							echo "Installed AdGuardHome version ($agh_version) doesn't support 'ipset_file' option!\\n"
						fi
					else
						echo "Resolver set support (${resolver_set}) is enabled in $packageName, but this resolver set is not supported on this system!\\n"
					
					fi
```

Can you run that piece of code on your system?

**Comment by stangri** [comment]
> If needed, I could install adguardhome ipk from master

That's what I'm testing with, but the necessary version hasn't been backported to 22.03 yet.

**Comment by bonuzzz** [comment]
```
#!/bin/sh 

readonly agh="$(command -v AdGuardHome)"
readonly aghConfigFile='/etc/AdGuardHome.yaml'
is_greater_or_equal() { test "$(printf '%s\n' "$@" | sort -V | head -n 1)" = "$2"; }


					if [ -n "$agh" ] && [ -s "$aghConfigFile" ]; then
						agh_version="$($agh --version | sed 's|AdGuard Home, version v0\.\(.*\)|\1|')"
						if is_greater_or_equal "$agh_version" '107.13'; then
							resolver_set_supported='true'
echo 'success'!
						else
							echo "Installed AdGuardHome version ($agh_version) doesn't support 'ipset_file' option!\\n"
						fi
					else
						echo "Resolver set support (${resolver_set}) is enabled in $packageName, but this resolver set is not supported on this system!\\n"
					
					fi
```

root@dacha:~# sh 4.sh
: not found2:
4.sh: line 19: syntax error: unexpected "fi" (expecting "then")

**Comment by bonuzzz** [comment]
I deleted previous message. It was my fault there.
Script said success

**Comment by stangri** [comment]
Well, that exact code is working on pbr start. I don't understand why it's working on its own, but not when part of the script.

**Comment by stangri** [comment]
Also, the screenshot you've posted 6 hours ago seems to confirm that WebUI has properly detected AGH ipset suppport.

**Comment by bonuzzz** [comment]
I've installed latest ipk from snapshot and two news. One bad news is new config filename is /etc/adguardhome.yaml without capital letters. Good news is after edit filename in script pbr finds adguardhome ipset

upd: seems the filename is never changed in openwrt repository.
I will use this installation couple days and will write you how it works. 
Big thanks for your support!

**Comment by stangri** [comment]
> upd: seems the filename is never changed in openwrt repository.

Yeah, looks like it's always been lower case: https://github.com/openwrt/packages/blob/openwrt-22.03/net/adguardhome/Makefile#L48. Weird that the new package installation didn't bring the yaml file for me.

I've copied your config from the zip-file you've posted above and it was camelized, so I never checked the package sources what the proper name is.

 PS. All fixed in `pbr 0.9.9-35`.

**Comment by bonuzzz** [comment]
It's me again:)
1. You forgot to change filename in luci.pbr https://github.com/stangri/source.openwrt.melmac.net/blob/master/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr#L23
2.  Additional dependencies for adh resolver ipset: ipset and iptables-nft
3. Probably it's better to use restart adh than reload, because seems agh doesn't read ipset file for changes during reload (not sure here)
4. Could you add sed to remove ipset filepath in agh config when stop using adh as resolver set?
5. When using agh resolver set, but not any rules are activated, ipset file doesn't created and agh stopped with error. Ipset file for agh should be always created , even empty

**Comment by stangri** [comment]
@bonuzzz thanks for the continuing feedback and testing!

> 1. You forgot to change filename in luci.pbr https://github.com/stangri/source.openwrt.melmac.net/blob/master/luci-app-pbr/root/usr/libexec/rpcd/luci.pbr#L23

Fixed in 0.9.9-36.

> 2. Additional dependencies for adh resolver ipset: ipset and iptables-nft

The ipset and iptables should be dependencies for the `pbr-iptables`, as the `pbr` has been designed for fw4/nft, these are not really required. AGH should bring those in actually.

> 3. Probably it's better to use restart adh than reload, because seems agh doesn't read ipset file for changes during reload (not sure here)

While there is the `reload` parameter to the `resolver()` function, it's not currently used, the `resolver 'restart'` is always used than the hashes of the old and new ipset/nftset files do not match.

> 4. Could you add sed to remove ipset filepath in agh config when stop using adh as resolver set?

Fixed in 0.9.9-36.

> 5. When using agh resolver set, but not any rules are activated, ipset file doesn't created and agh stopped with error. Ipset file for agh should be always created , even empty

Fixed in 0.9.9-36.

**Comment by bonuzzz** [comment]
About packages I wrote just for documentation if someone wants to use pbr with adguardhome. I use pbr package in 22.03.
What about the issue when adguardhome doesn't populate ipset. I had this at starting system. So, solution is simple: adguardhome should NOT be enabled in autostart in openwrt. Pbr starts it anyway, but in this case ipset population works immediately.

As luci-app-adguardhome ( https://github.com/kongfl888/luci-app-adguardhome ) is mentioned on adguaghome site and this is simple enough method to use actual agh version on openwrt, I will write the difference in config and filenames between it and package from repository. Maybe you could add support both variants of agh usage.

**Comment by stangri** [comment]
> What about the issue when adguardhome doesn't populate ipset. I had this at starting system. So, solution is simple: adguardhome should NOT be enabled in autostart in openwrt. Pbr starts it anyway, but in this case ipset population works immediately.

You mean that AGH can't start if the ipset_file is empty? It should be addressed in the AGH OpenWrt package init script, it should touch that file before launching the binary.



> As luci-app-adguardhome ( https://github.com/kongfl888/luci-app-adguardhome ) is mentioned on adguaghome site and this is simple enough method to use actual agh version on openwrt, I will write the difference in config and filenames between it and package from repository. Maybe you could add support both variants of agh usage.

So that luci app packages its own binary and the init scripts which use a different location for config yaml? I'm reluctant to support it for two reasons:
1. There's already (supported) AGH package in the official repo.
2. The (unofficial) luci app is written in Lua which will be phased out soon anyways.

**Comment by bonuzzz** [comment]
No. If agh is enabled in autostart, so everything starts as usual and ipset file for agh is exist with rules, but agh doesn't populate ipset itself with ips. To get agh start populating ipset, I have to restart agh.

Some more word about iptables-nft. If I don't install this package I have this error on screenshot
I use pbr package and luci-app-pbr on 22.03
<img width="874" alt="Screenshot 2022-11-21 at 01 29 35" src="https://user-images.githubusercontent.com/6509127/202930323-6c78362c-b477-4101-bc4c-40c14a4cfdd6.png">
 I write just to clarify this is normal or not
