### ISSUE TITLE
[pbr] issue: Inconsistent routing with PBR/OpenVPN

### ISSUE THREAD

**Issue by posita** [stangri/openwrt_packages#180]
**Describe the bug**

I have a router configured as an OpenVPN client, and I use PBR to whitelist some domains and subdomains to be routed over my wan. I have noticed that after a period of time, the whitelisted domains and subdomains eventually revert to being routed over the VPN. It's unclear to me why/when this happens. I can almost always cure this by restarting `openvpn` and waiting a few seconds (maybe a minute tops). But it will eventually revert to trying to route those domains and subdomains over the VPN. I am not rebooting the router in the mean time, nor do I have any cron jobs or anything that periodically reset the VPN connection.

**Your configs**

1. ```/etc/config/dhcp```

```sh

config dnsmasq
	option domainneeded '1'
	option boguspriv '1'
	option filterwin2k '0'
	option localise_queries '1'
	option rebind_protection '1'
	option rebind_localhost '1'
	option local '/lan/'
	option expandhosts '1'
	option nonegcache '0'
	option authoritative '1'
	option readethers '1'
	option leasefile '/tmp/dhcp.leases'
	option resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'
	option nonwildcard '1'
	option localservice '1'
	option ednspacket_max '1232'
	option domain 'panda'
	option sequential_ip '1'
	list server '9.9.9.9'
	list server '149.112.112.112'
	list server '/airdns.org/52.48.66.85'
	list server '/airdns.org/54.225.156.17'
	option confdir '/tmp/dnsmasq.d'

config dhcp 'lan'
	option interface 'lan'
	option leasetime '12h'
	option dhcpv4 'server'
	option start '258'
	option limit '253'

config dhcp 'wan'
	option interface 'wan'
	option ignore '1'

config odhcpd 'odhcpd'
	option maindhcp '0'
	option leasefile '/tmp/hosts/odhcpd'
	option leasetrigger '/usr/sbin/odhcpd-update'
	option loglevel '4'

config domain
	option name 'modem'
	option ip '192.168.100.1'
   ```

2. ```/etc/config/network```

```sh

config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'

config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'lan1'
	list ports 'lan2'
	list ports 'lan3'
	list ports 'lan4'

config interface 'lan'
	option proto 'static'
	option ipv6 '0'
	option delegate '0'
	option ipaddr '192.168....'
	option netmask '255.255.254.0'
	option device 'br-lan.1'

config device
	option name 'wan'
	option macaddr '...'

config interface 'wan'
	option device 'wan'
	option proto 'dhcp'
	option hostname '*'
	option ipv6 '0'
	option peerdns '0'

config interface 'wan6'
	option device 'wan'
	option auto '0'
	option proto 'none'
	option delegate '0'
	option peerdns '0'
   ```

3. ```/etc/config/firewall```

```sh

config defaults
	option syn_flood '1'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'REJECT'

config zone
	option name 'lan'
	list network 'lan'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'REJECT'

config zone
	option name 'wan'
	list network 'wan'
	list network 'wan6'
	option input 'REJECT'
	option output 'ACCEPT'
	option forward 'REJECT'
	option masq '1'
	option mtu_fix '1'

config forwarding
	option src 'lan'
	option dest 'wan'

config rule
	option name 'Allow-DHCP-Renew'
	option src 'wan'
	option proto 'udp'
	option dest_port '68'
	option target 'ACCEPT'
	option family 'ipv4'

config rule
	option name 'Allow-Ping'
	option src 'wan'
	option proto 'icmp'
	option icmp_type 'echo-request'
	option family 'ipv4'
	option target 'ACCEPT'

config rule
	option name 'Allow-IGMP'
	option src 'wan'
	option proto 'igmp'
	option family 'ipv4'
	option target 'ACCEPT'

config rule
	option name 'Allow-DHCPv6'
	option src 'wan'
	option proto 'udp'
	option dest_port '546'
	option family 'ipv6'
	option target 'ACCEPT'

config rule
	option name 'Allow-MLD'
	option src 'wan'
	option proto 'icmp'
	option src_ip 'fe80::/10'
	list icmp_type '130/0'
	list icmp_type '131/0'
	list icmp_type '132/0'
	list icmp_type '143/0'
	option family 'ipv6'
	option target 'ACCEPT'

config rule
	option name 'Allow-ICMPv6-Input'
	option src 'wan'
	option proto 'icmp'
	list icmp_type 'echo-request'
	list icmp_type 'echo-reply'
	list icmp_type 'destination-unreachable'
	list icmp_type 'packet-too-big'
	list icmp_type 'time-exceeded'
	list icmp_type 'bad-header'
	list icmp_type 'unknown-header-type'
	list icmp_type 'router-solicitation'
	list icmp_type 'neighbour-solicitation'
	list icmp_type 'router-advertisement'
	list icmp_type 'neighbour-advertisement'
	option limit '1000/sec'
	option family 'ipv6'
	option target 'ACCEPT'

config rule
	option name 'Allow-ICMPv6-Forward'
	option src 'wan'
	option dest '*'
	option proto 'icmp'
	list icmp_type 'echo-request'
	list icmp_type 'echo-reply'
	list icmp_type 'destination-unreachable'
	list icmp_type 'packet-too-big'
	list icmp_type 'time-exceeded'
	list icmp_type 'bad-header'
	list icmp_type 'unknown-header-type'
	option limit '1000/sec'
	option family 'ipv6'
	option target 'ACCEPT'

config rule
	option name 'Allow-IPSec-ESP'
	option src 'wan'
	option dest 'lan'
	option proto 'esp'
	option target 'ACCEPT'

config rule
	option name 'Allow-ISAKMP'
	option src 'wan'
	option dest 'lan'
	option dest_port '500'
	option proto 'udp'
	option target 'ACCEPT'

config zone
	option name 'vpnclient'
	option device 'ovpnc0'
	option input 'REJECT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
	option masq '1'
	option mtu_fix '1'

config forwarding
	option src 'lan'
	option dest 'vpnclient'

config include 'pbr'
	option fw4_compatible '1'
	option type 'script'
	option path '/usr/share/pbr/pbr.firewall.include'
   ```

4. ```/etc/config/pbr```

```sh

config pbr 'config'
	option verbosity '2'
	option strict_enforcement '1'
	option ipv6_enabled '0'
	list ignored_interface 'vpnserver'
	list ignored_interface 'wgserver'
	option boot_timeout '30'
	option rule_create_option 'add'
	option procd_reload_delay '1'
	option webui_show_ignore_target '0'
	list webui_supported_protocol 'all'
	list webui_supported_protocol 'tcp'
	list webui_supported_protocol 'udp'
	list webui_supported_protocol 'tcp udp'
	list webui_supported_protocol 'icmp'
	option enabled '1'
	option resolver_set 'dnsmasq.ipset'
	list supported_interface 'ovpnc0'

config include
	option path '/usr/share/pbr/pbr.user.aws'
	option enabled '0'

config include
	option path '/usr/share/pbr/pbr.user.netflix'
	option enabled '0'

config policy
	option name 'Plex/Emby Local Server'
	option interface 'wan'
	option src_port '8096 8920 32400'
	option enabled '0'

config policy
	option name 'Plex/Emby Remote Servers'
	option interface 'wan'
	option dest_addr 'plex.tv my.plexapp.com emby.media app.emby.media tv.emby.media'
	option enabled '0'

config policy
	option name 'WireGuard Server'
	option interface 'wan'
	option src_port '51820'
	option chain 'output'
	option proto 'udp'
	option enabled '0'

config policy
	option name '192.168.100.1'
	option dest_addr '192.168.100.1'
	option interface 'wan'

config policy
	option name 'cds.audible.com'
	option dest_addr 'cds.audible.com'
	option interface 'wan'

config policy
	option name 'reg.usps.com'
	option dest_addr 'reg.usps.com'
	option interface 'wan'
   ```

**To Reproduce**
1. Reboot router
2. `traceroute reg.usps.com`
3. Note that it goes through the VPN
4. `/etc/init.d/openvpn restart`
5. `traceroute reg.usps.com`
6. Note that it still goes through the VPN
7. Wait about a minute
8. `traceroute reg.usps.com`
9. Note that it goes through `lan`
10. Wait a few hours
11. `traceroute reg.usps.com`
12. Note that it goes through the VPN again

**Expected behavior**
I kind of expected that once PBR gets spooled up for the route to stabilize as configured. If anything it seems to stabilize on the domain/subdomain whitelist being ignored/ineffective.

**VPN Policy Routing run-time information**

1. Output of ```/etc/init.d/pbr reload``` with ```verbosity``` set to 2:

```sh
root@...:~# /etc/init.d/pbr reload
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Activating traffic killswitch [✓]
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
Setting up routing for 'wan/...' [✓]
Routing '192.168.100.1' via wan [✓]
Routing 'cds.audible.com' via wan [✓]
Routing 'reg.usps.com' via wan [✓]
Deactivating traffic killswitch [✓]
pbr 1.0.1-3 monitoring interfaces: wan
pbr 1.0.1-3 (iptables) started with gateways:
wan/...
   ```

2. Output of ```/etc/init.d/pbr support```:

```sh
root@...:~# /etc/init.d/pbr support
Syntax: /etc/init.d/pbr [command]

Available commands:
        start           Start the service
        stop            Stop the service
        restart         Restart the service
        reload          Reload configuration files (or restart if service does not implement reload)
        enable          Enable service autostart
        disable         Disable service autostart
        enabled         Check if service is started on boot
        status          Generates output required to troubleshoot routing issues
                Use '-d' option for more detailed output
                Use '-p' option to automatically upload data under VPR paste.ee account
                        WARNING: while paste.ee uploads are unlisted, they are still publicly available
                List domain names after options to include their lookup in report
        version         Show version information
        on_firewall_reload      Run service on firewall reload
        on_interface_reload     Run service on indicated interface reload
        running         Check if service is running
        status          Service status
        trace           Start with syscall trace
        info            Dump procd service info

   ```

Content above has been slightly redacted to minimize identifying information.

**Comment by posita** [comment]
If it's helpful for diagnostic purposes, I was experiencing similar issues with `vpn-policy-router`. (I know that's no longer being developed, but I mention it only in case it's a useful data point.)

Also, (FYI) I had to hand-correct the issue template formatting to get it to render correctly. The template has lines where code block entries are prefixed by white space which messes with things. E.g.:

```
    ```sh
This won't render properly.
    ```
```

**Comment by stangri** [comment]
1. Your network file is missing VPN Client interface definition as recommended in the pbr README.
2. Which device are you running traceroute on?
3. Please provide the output of `service pbr status` in the failed routing state.

**Comment by stangri** [comment]
1. Your network file is missing VPN Client interface definition as recommended in the pbr README.
1. Which device are you running traceroute on?

Please provide the output of `service pbr status` in the failed routing state.

> If it's helpful for diagnostic purposes, I was experiencing similar issues with `vpn-policy-router`. (I know that's no longer being developed, but I mention it only in case it's a useful data point.)
> 
> Also, (FYI) I had to hand-correct the issue template formatting to get it to render correctly. The template has lines where code block entries are prefixed by white space which messes with things. E.g.:
> 
> ```
>     ```sh
> This won't render properly.
>     ```
> ```

Fixed in https://github.com/stangri/source.openwrt.melmac.net/commit/22cf54bc4cdc6e8477f7b8cece14773431fca8d7

**Comment by stangri** [comment]
> If it's helpful for diagnostic purposes, I was experiencing similar issues with `vpn-policy-router`. (I know that's no longer being developed, but I mention it only in case it's a useful data point.)
> 
> Also, (FYI) I had to hand-correct the issue template formatting to get it to render correctly. The template has lines where code block entries are prefixed by white space which messes with things. E.g.:
> 
> ```
>     ```sh
> This won't render properly.
>     ```
> ```

Fixed in https://github.com/stangri/source.openwrt.melmac.net/commit/22cf54bc4cdc6e8477f7b8cece14773431fca8d7

**Comment by posita** [comment]
> Your network file is missing VPN Client interface definition as recommended in the pbr README.

This [this](https://docs.openwrt.melmac.net/pbr/#basic-openvpn-client-config) the section to which you're referring? (There's a lot there and the organization is hard to navigate from a user perspective. I want to be sure I'm looking in the correct spot.)

> Which device are you running traceroute on?

A client machine connected to the router via its WiFi interface.

```
pbr 1.0.1-3 running on OpenWrt 22.03.2. WAN (IPv4): wan/wan/....
============================================================
Dnsmasq version 2.86  Copyright (c) 2000-2021 Simon Kelley
Compile time options: IPv6 GNU-getopt no-DBus UBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth cryptohash DNSSEC no-ID loop-detect inotify dumpfile
============================================================
Routes/IP Rules
default         10.xx.xx.1     128.0.0.0       UG    0      0        0 ovpnc0
default         ... 0.0.0.0         UG    0      0        0 wan
IPv4 table 256 route: default via ... dev wan 
IPv4 table 256 rule(s):
30000:	from all fwmark 0x10000/0xff0000 lookup pbr_wan
============================================================
Mangle IP Table: FORWARD
# Warning: iptables-legacy tables present, use iptables-legacy to see them
-N PBR_FORWARD
============================================================
Mangle IP Table: INPUT
# Warning: iptables-legacy tables present, use iptables-legacy to see them
-N PBR_INPUT
============================================================
Mangle IP Table: OUTPUT
# Warning: iptables-legacy tables present, use iptables-legacy to see them
-N PBR_OUTPUT
============================================================
Mangle IP Table: POSTROUTING
# Warning: iptables-legacy tables present, use iptables-legacy to see them
-N PBR_POSTROUTING
============================================================
Mangle IP Table: PREROUTING
# Warning: iptables-legacy tables present, use iptables-legacy to see them
-N PBR_PREROUTING
-A PBR_PREROUTING -d 192.168.100.1/32 -m comment --comment 192_168_100_1 -c 0 0 -g PBR_MARK_0x010000
-A PBR_PREROUTING -m set --match-set pbr_wan_4_dst_ip_cfg086ff5 dst -m comment --comment cds_audible_com -c 0 0 -g PBR_MARK_0x010000
-A PBR_PREROUTING -m set --match-set pbr_wan_4_dst_ip_cfg096ff5 dst -m comment --comment reg_usps_com -c 0 0 -g PBR_MARK_0x010000
============================================================
Mangle IP Table MARK Chain: PBR_MARK_0x010000
# Warning: iptables-legacy tables present, use iptables-legacy to see them
-N PBR_MARK_0x010000
-A PBR_MARK_0x010000 -c 0 0 -j MARK --set-xmark 0x10000/0xff0000
-A PBR_MARK_0x010000 -c 0 0 -j RETURN
============================================================
Current ipsets
create pbr_wan_4_dst_ip_cfg076ff5 hash:ip family inet hashsize 1024 maxelem 65536 comment
create pbr_wan_4_dst_ip_cfg086ff5 hash:ip family inet hashsize 1024 maxelem 65536 comment
create pbr_wan_4_dst_ip_cfg096ff5 hash:ip family inet hashsize 1024 maxelem 65536 comment
============================================================
DNSMASQ sets
ipset=/cds.audible.com/pbr_wan_4_dst_ip_cfg086ff5 # cds.audible.com: cds.audible.com
ipset=/reg.usps.com/pbr_wan_4_dst_ip_cfg096ff5 # reg.usps.com: reg.usps.com
============================================================
Your support details have been logged to '/var/pbr-support'. [0;32m[✓][0m
```

**Comment by stangri** [comment]
> This [this](https://docs.openwrt.melmac.net/pbr/#basic-openvpn-client-config) the section to which you're referring?

Yes.

> pbr 1.0.1-3 running on OpenWrt 22.03.2.

In your steps to reproduce, did you omit the step where you deleted something from the `pbr` config? 

Based on the output, I see that the ipsets have been created and correctly targeted by iptables, however ipsets have not been populated with the resolved IPs. Most likely is that `dnsmasq` is being restarted and the LAN client either cached the DNS response so it doesn't send a DNS request for affected domain (so `dnsmasq` doesn't resolve it and doesn't populate the relevant ipset) and/or client uses a different resolver altogether (so `dnsmasq` doesn't resolve the domain and doesn't populate the relevant ipset). I don't see anything broken in `pbr`.

**Comment by posita** [comment]
Okay, thanks. Since the problem takes a few hours to manifest, can you give me a day or two to reset configs on my end and see if I still experience the issue? I'll close it or report back with an update.

**Comment by posita** [comment]
I added the following to my `/etc/config/network` file:

```
config interface 'vpnclient'
	option proto 'none'
	option device 'ovpnc0'
```

I originally added `iface` instead of `device`, but when navigating to `.../cgi-bin/luci/admin/network/network`, I was informed that configuration would be automatically changed. The above is the result. (Maybe worth a doc change?)

`pbr` routing now seems more stable. However, if I ever restart `openvpn` (e.g., to reconnect to a different exit point), no whitelisted routing is possible until after I do `/etc/init.d/pbr restart` (or `reload`) as well (and even then, it can take quite awhile for the effects to be seen). That also may be worth documenting?

Closing, since the original issue _seems_ like it's resolved? I'll reopen if I discover otherwise.

**Comment by stangri** [comment]
Does the firewall get restarted/reloaded when you restart OpenVPN? Sadly, OpenVPN does not create the netifd-compatible interfaces, so even when `pbr` tries to register to be notified of the OpenVPN interface changes, I don't think it ever does (get notified). In `vpn-policy-routing` I used a firewall hotplug to reload the service on OpenVPN reloads and I'm using a different script for firewall4. Is it no longer working with `pbr`?

PS. Thanks for mentioning docs needed a fix: https://github.com/stangri/docs.openwrt.melmac.net/commit/cc9c6e0ab0b91c98567cca07c7dcfea97c582a6f

**Comment by posita** [comment]
Give me a bit to test again to make sure I'm observing the symptoms correctly.

**Comment by posita** [comment]
After additional testing on my end, it looks like there's a lag, but eventually, `pbr` resets after `openvpn restart`. My observation(s) were probably a result of either: 1) not waiting long enough; or 2) caused by me mucking with other things trying to diagnose. I think this can be closed, since it does indeed appear that `pbr` is behaving as designed. Apologies for the false alarm!
